
development:
  adapter: postgresql
  encoding: unicode
  database: angrybirds_development
  pool: 5
  username: javier
  password: javier


test:
  adapter: postgresql
  encoding: unicode
  database: angrybirds_test
  pool: 5
  username: javier
  password: javier

production:
  adapter: postgresql
  encoding: unicode
  database: angrybirds_production
  pool: 5
  username: javier
  password: javier
