
development:
  adapter: mysql2
  pool: 5
  host: localhost
  username: root
  password: root
  database: angrybirds_dev

test:
  adapter: mysql2
  pool: 5
  host: localhost
  username: root
  password: root
  database: angrybirds_test


production:
  adapter: postgresql
  encoding: unicode
  database: angrybirds_production
  pool: 5
  username: javier
  password: javier
